# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieRoomApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SDWebImage', '~>5.0'
  pod 'Alamofire'
  pod 'ProgressHUD'
  pod 'KeychainAccess'
  pod 'PanModal'
  pod 'Localize-Swift', '~>3.2'
  pod 'OneSignalXCFramework', '>= 3.0.0', '< 4.0'

end
